### ISSUE TITLE
Fix issues with ESLint

### ISSUE THREAD

**Issue by ALEGATOR1209** [AlmostGreatBand/lemon-server#24]
ESLint doesn't recognise new syntax with private fields + add ESLint checks to CI configuration

**Comment by Hud-Volodymyr** [comment]
@ALEGATOR1209 Do we want to add babel to fix private fields issue? It seems like eslint doesn't support them out of the box

**Comment by ALEGATOR1209** [comment]
Is it? Really strange, but if we add babel then we'll check not all code but transpiled, won't we?

**Comment by Hud-Volodymyr** [comment]
Private fields are still not accepted by ECMA that eslint implements so it's probably better not to use them, if we want to avoid babel

**Comment by ALEGATOR1209** [comment]
Agreed, we won't use them

**Comment by ALEGATOR1209** [comment]
So I gonna close this, we'll fix it in #25
